# Generated by Django 5.1.4 on 2025-09-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='saddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='smobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sname',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
